#!/usr/bin/env bash
# Copyright (c) 2026 Godwit.io
#
# Licensed under the MIT License. You may obtain a copy of the License at
#
#     https://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# init-garage.sh — Bootstrap a single-node Garage cluster:
#   1. Wait for the Garage daemon to be ready
#   2. Assign layout (capacity + zone)
#   3. Create the demo-bucket
#   4. Create an S3 key and grant bucket access
#   5. Write credentials to .credentials (sourced by migrate.sh)

set -euo pipefail

COMPOSE_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/infra/docker-compose.yml"
CREDENTIALS_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.credentials"
CONTAINER="godwit-lab-garage"
GARAGE_BIN="/garage"

# ── Wait for Garage ────────────────────────────────────────────────────────────
echo "==> Waiting for Garage daemon ..."
until docker exec "${CONTAINER}" "${GARAGE_BIN}" status >/dev/null 2>&1; do
  printf "    not ready yet, retrying in 3s ...\r"
  sleep 3
done
echo "    Garage daemon is up."

# ── Assign layout ──────────────────────────────────────────────────────────────
echo ""
echo "==> Configuring cluster layout ..."

NODE_ID=$(docker exec "${CONTAINER}" "${GARAGE_BIN}" node id 2>/dev/null \
  | head -1 \
  | sed 's/@.*//' \
  | tr -d ' \r\n')

echo "    Node ID: ${NODE_ID}"

LAYOUT_OUTPUT=$(docker exec "${CONTAINER}" "${GARAGE_BIN}" layout show 2>&1)

if echo "${LAYOUT_OUTPUT}" | grep -q "No nodes currently have a role"; then
  docker exec "${CONTAINER}" \
    "${GARAGE_BIN}" layout assign "${NODE_ID}" --capacity 1G -z dc1

  docker exec "${CONTAINER}" \
    "${GARAGE_BIN}" layout apply --version 1

  echo "    Layout applied."
else
  echo "    Layout already configured — skipping."
fi

# ── Create bucket ──────────────────────────────────────────────────────────────
echo ""
echo "==> Creating bucket 'demo-bucket' ..."
docker exec "${CONTAINER}" "${GARAGE_BIN}" bucket create demo-bucket 2>/dev/null \
  || echo "    (bucket already exists — OK)"

# ── Create key ─────────────────────────────────────────────────────────────────
echo ""
echo "==> Creating S3 key 'garageadmin' ..."
KEY_OUTPUT=$(docker exec "${CONTAINER}" "${GARAGE_BIN}" key create garageadmin 2>&1)

GARAGE_KEY_ID=$(echo "${KEY_OUTPUT}" \
  | grep -i "Key ID" \
  | grep -v "Key name" \
  | awk '{print $NF}' \
  | tr -d '\r ')

GARAGE_SECRET=$(echo "${KEY_OUTPUT}" \
  | grep -i "Secret key" \
  | awk '{print $NF}' \
  | tr -d '\r ')

if [[ -z "${GARAGE_KEY_ID}" || -z "${GARAGE_SECRET}" ]]; then
  echo "ERROR: Could not parse key credentials from garage output:"
  echo "${KEY_OUTPUT}"
  exit 1
fi

# ── Grant bucket access ────────────────────────────────────────────────────────
echo ""
echo "==> Granting key access to 'demo-bucket' ..."
docker exec "${CONTAINER}" \
  "${GARAGE_BIN}" bucket allow --read --write --owner demo-bucket --key "${GARAGE_KEY_ID}"

# ── Write credentials file ─────────────────────────────────────────────────────
cat > "${CREDENTIALS_FILE}" << EOF
# Garage credentials — generated by init-garage.sh
# Do not commit this file.
GARAGE_ACCESS_KEY=${GARAGE_KEY_ID}
GARAGE_SECRET_KEY=${GARAGE_SECRET}
EOF

echo ""
echo "==> Garage initialized."
echo "    Bucket:     demo-bucket"
echo "    Access key: ${GARAGE_KEY_ID}"
echo "    Secret key: ${GARAGE_SECRET}"
echo "    Credentials written to: .credentials"
echo ""
echo "Next step:"
echo "  bash scripts/migrate.sh"
